### ISSUE TITLE
remove st peripheral lib and port to libopencm3

### ISSUE THREAD

**Issue by fishpepper** [fishpepper/OpenGround#6]
I just started to port this to use the open libopencm3 instead of the st peripheral libraries. 
see branch opencm3 (not working yet)

**Comment by rav-rav** [comment]
I've been messing with the USART libraries to get the 4-in-1 multimodule running: https://github.com/rav-rav/OpenGround
Hopefully it will be easy to port this to libopencm3.
Did you get the mail I've sent to info fishpepper.de?

**Comment by fishpepper** [comment]
Should be no problem, libopencm3 looks quite clean to me. Actually it looks much cleaner than the st version...

**Comment by jacobbloy** [comment]
Iv added USB HID support and done a pull request, I hope you can still do the port to libopencm3 while keeping the changes I have made.

**Comment by fishpepper** [comment]
thanks for that, it is integrated in opencm branch and master now.
